

let NJcodemap = [
"NJ37169","Aberdeen-Matawan","AM",
"NJ2","Absecon","AB",
"NJ3","Allendale","AZ",
"NJ4","Allenhurst","AH",
"NJ5","Anderson Street","AS",
"NJ6","Annandale","AN",
"NJ8","Asbury Park","AP",
"NJ9","Atco","AO",
"NJ10","Atlantic City Rail Terminal","AC",
"NJ11","Avenel","AV",
"AMSBWI","BWI Thurgood Marshall Airport","BA",
"AMSBAL","Baltimore Station","BL",
"NJ12","Basking Ridge","BI",
"NJ13","Bay Head","BH",
"NJ14","Bay Street","MC",
"NJ15","Belmar","BS",
"NJ17","Berkeley Heights","BY",
"NJ18","Bernardsville","BV",
"NJ19","Bloomfield","BM",
"NJ20","Boonton","BN",
"NJ21","Bound Brook","BK",
"NJ22","Bradley Beach","BB",
"NJ23","Brick Church","BU",
"NJ24","Bridgewater","BW",
"NJ25","Broadway Fair Lawn","BF",
"NJ26","Campbell Hall","CB",
"NJ27","Chatham","CM",
"NJ28","Cherry Hill","CY",
"NJ29","Clifton","IF",
"NJ30","Convent Station","CN",
"NJ32","Cranford","XC",
"NJ33","Delawanna","DL",
"NJ34","Denville","DV",
"NJ35","Dover","DO",
"NJ36","Dunellen","DN",
"NJ37","East Orange","EO",
"NJ38","Edison","ED",
"NJ39","Egg Harbor City","EH",
"NJ40","Elberon","EL",
"NJ41","Elizabeth","EZ",
"NJ42","Emerson","EN",
"NJ43","Essex Street","EX",
"NJ44","Fanwood","FW",
"NJ45","Far Hills","FH",
"","Finderne","FE",
"NJ46","Garfield","GD",
"NJ47","Garwood","GW",
"NJ48","Gillette","GI",
"NJ49","Gladstone","GL",
"NJ50","Glen Ridge","GG",
"NJ51","Glen Rock Boro Hall","GK",
"NJ52","Glen Rock Main Line","RS",
"","Great Notch","GA",
"NJ54","Hackettstown","HQ",
"NJ32905","Hamilton","HL",
"NJ55","Hammonton","HN",
"NJ57","Harriman","RM",
"NJ58","Hawthorne","HW",
"NJ59","Hazlet","HZ",
"NJ60","High Bridge","HG",
"NJ61","Highland Avenue","HI",
"NJ62","Hillsdale","HD",
"NJ63","Hoboken","HB",
"NJ64","Hohokus","UF",
"NJ32906","Jersey Avenue","JA",
"NJ66","Kingsland","KG",
"NJ67","Lake Hopatcong","HP",
"NJ68","Lebanon","ON",
"NJ69","Lincoln Park","LP",
"NJ70","Linden","LI",
"NJ71","Lindenwold","LW",
"NJ72","Little Falls","FA",
"NJ73","Little Silver","LS",
"NJ74","Long Branch","LB",
"NJ75","Lyndhurst","LN",
"NJ76","Lyons","LY",
"NJ77","Madison","MA",
"NJ78","Mahwah","MZ",
"NJ79","Manasquan","SQ",
"NJ81","Maplewood","MW",
"NJ40570","Meadowlands","XU",
"NJ83","Metropark","MP",
"NJ84","Metuchen","MU",
"NJ85","Middletown NJ","MI",
"NJ86","Middletown NY","MD",
"NJ87","Millburn","MB",
"NJ88","Millington","GO",
"NJ31696","Monmouth Park","MK",
"NJ89","Montclair Heights","HS",
"NJ38081","Montclair State U","UV",
"NJ90","Montvale","ZM",
"NJ91","Morris Plains","MX",
"NJ92","Morristown","MR",
"NJ39472","Mount Arlington","HV",
"NJ94","Mount Olive","OL",
"NJ97","Mount Tabor","TB",
"NJ95","Mountain Avenue","MS",
"NJ96","Mountain Lakes","ML",
"NJ97","Mountain Station","MT",
"NJ98","Mountain View","MV",
"NJ99","Murray Hill","MH",
"NJ100","Nanuet","NN",
"NJ101","Netcong","NT",
"NJ102","Netherwood","NE",
"NJ110","New Bridge Landing","NH",
"NJ103","New Brunswick","NB",
"AMSNCR","New Carrollton Station","NC",
"NJ104","New Providence","NV",
"NJ105","New York Penn Station","NY",
"NJ37953","Newark Airport","NA",
"NJ106","Newark Broad Street","ND",
"NJ107","Newark Penn Station","NP",
"NJ108","North Branch","OR",
"NJ109","North Elizabeth","NZ",
"AMSPHN","North Philadelphia","NF",
"NJ111","Oradell","OD",
"NJ112","Orange","OG",
"NJ113","Otisville","OS",
"NJ114","Park Ridge","PV",
"NJ115","Passaic","PS",
"NJ116","Paterson","RN",
"NJ117","Peapack","PC",
"NJ118","Pearl River","PQ",
"NJ43298","Pennsauken","PN",
"NJ119","Perth Amboy","PE",
"NJ1","Philadelphia","PH",
"NJ120","Plainfield","PF",
"NJ121","Plauderville","PL",
"NJ122","Point Pleasant Beach","PP",
"NJ123","Port Jervis","PO",
"NJ124","Princeton","PR",
"NJ125","Princeton Junction","PJ",
"NJ126","Radburn Fair Lawn","FZ",
"NJ127","Rahway","RH",
"NJ128","Ramsey Main St","RY",
"NJ38417","Ramsey Route 17","17",
"NJ129","Raritan","RA",
"NJ130","Red Bank","RB",
"NJ131","Ridgewood","RW",
"NJ132","River Edge","RG",
"NJ31","Roselle Park","RL",
"NJ134","Rutherford","RF",
"NJ135","Salisbury Mills-Cornwall","CW",
"","Secaucus Concourse","SC",
"NJ38174","Secaucus Lower Lvl","TS",
"NJ38187","Secaucus Upper Lvl","SE",
"NJ136","Short Hills","RT",
"NJ137","Sloatsburg","XG",
"NJ138","Somerville","SM",
"NJ139","South Amboy","CH",
"NJ140","South Orange","SO",
"NJ141","Spring Lake","LA",
"NJ142","Spring Valley","SV",
"NJ143","Stirling","SG",
"NJ144","Suffern","SF",
"NJ145","Summit","ST",
"NJ146","Teterboro","TE",
"NJ147","Towaco","TO",
"NJ148","Trenton","TR",
"NJ149","Tuxedo","TC",
"NJ38105","Union","US",
"NJ150","Upper Montclair","UM",
"NJ151","Waldwick","WK",
"NJ152","Walnut Street","WA",
"AMSWAS","Washington Station","WS",
"NJ153","Watchung Avenue","WG",
"NJ154","Watsessing Avenue","WT",
"NJ39635","Wayne-Route 23","23",
"NJ43599","Wesmont","WM",
"NJ155","Westfield","WF",
"NJ156","Westwood","WW",
"NJ157","White House","WH",
"AMSWIL","Wilmington Station","WI",
"NJ160","Wood Ridge","WR",
"NJ158","Woodbridge","WB",
"NJ159","Woodcliff Lake","WL"
];

let NJrouteCodes = [
,"Amtrak","LINEAM",
,"Atlantic City Line","AC",
,"Bergen County Line","BC",
,"BetMGM Meadowlands","SL",
,"Gladstone Branch","GS",
,"ME Line","ME",
,"Main Line","ML",
,"Montclair-Boonton Line","MC",
,"Morris & Essex Line","ME",
,"North Jersey Coast Line","NC",
,"Northeast Corridor Line","NE",
,"Pascack Valley Line","PV",
,"Princeton Branch","PR",
,"Raritan Valley Line","RV",
,"Septa","SP"
];


